@startuml
alice -> bob : hello
note left : this is a first note
bob -> alice : ok
note right : this is another note
bob -> bob : I am thinking
note left
    a note
    can also be defined
    on several lines
end note
@enduml
